import { useEffect, useMemo, useRef, useState } from 'react';

const photos = [
  [1,'cities','Victoria Harbour, Hong Kong','Moon over North Point. I waited for the water to go still and it never did, so I took it moving.'],[21,'cities','Mong Kok, Hong Kong','Rain, taxis, and a Jollibee sign three floors up. Felt closer to home than I expected it to.'],[5,'land','Batangas','Duranta in the neighbour’s hedge. The new leaves come in yellow before they settle into green.'],[19,'cities','Victoria Harbour, Hong Kong','Red sail against grey water and grey sky. The only colour in the whole frame, and it was moving fast.'],[16,'cities','Tsim Sha Tsui, Hong Kong','Blue hour on the harbour lasts about ten minutes. This is minute eight.'],[13,'cities','PUP, Manila','Stood under the flagpole waiting for enough wind to fill it. The sky did most of the work.'],[3,'land','Tagaytay, Cavite','Taal from the ridge, with the cloud deck sitting lower than the crater.'],[18,'cities','Avenue of Stars, Hong Kong','The only landscape frame in the set. Everyone on the promenade facing the same direction.'],[8,'structures','BGC, Manila','A parking ramp ceiling, looking straight up. Nobody designed this expecting anyone to look.'],[14,'structures','Taal Basilica, Batangas','Largest Catholic church in Asia. Up close you only get columns — the scale is impossible to frame.'],[20,'structures','Tsim Sha Tsui, Hong Kong','Canopy steelwork at dusk with one lamp still burning. Four members meeting at one node.'],[12,'light','Oil Street, Hong Kong','A lit doorframe in an art space. The entire street was black except for this one rectangle.'],[9,'structures','BGC, Manila','Lantern install in an office atrium. All that weight held by tension cables you can barely see.'],[17,'structures','Tsim Sha Tsui, Hong Kong','The Space Museum dome under a storm that never actually landed.'],[15,'structures','Taal Basilica, Batangas','Stepped back as far as the street allows. Still does not fit in the frame.'],[10,'light','Lipa, Batangas','Six in the morning heading to campus. The transmission tower landed exactly where the sun was.'],[11,'light','Lipa, Batangas','Speak Cafe at closing time — rice field on one side, new subdivision on the other.'],[6,'land','Tanay, Rizal','Rain cleared for maybe four minutes and left a full double arc over the valley.'],[7,'light','Tanay, Rizal','Same balcony, the evening before. The bulbs came on before the sun was done.'],[2,'cities','Central Piers, Hong Kong','The palm trunk is in the way. That is the reason I kept this one.'],[4,'cities','Binondo, Manila','Oldest Chinatown in the world, and the arch is still hand-painted.']
].map(([id,cat,place,note],index)=>({id,cat,place,note,number:String(index+1).padStart(2,'0'),src:`/images/gallery/${id}.jpg`,landscape:id===18}));
const categories=[['all','All'],['cities','Cities'],['structures','Structures'],['light','Light'],['land','Land']];
function pack(items,width){const count=width<620?2:width<1080?3:4;const weights=count===4?[4,3,5,3.4]:count===3?[4,3,5]:[1,1];const columns=weights.map(()=>[]),heights=weights.map(()=>0);items.forEach(photo=>{let column=0;for(let index=1;index<heights.length;index++)if(heights[index]<heights[column]-.0001)column=index;columns[column].push(photo);heights[column]+=weights[column]/(photo.landscape?1.3333:.75)});return{columns,weights}}

export default function Gallery(){
  const[category,setCategory]=useState('all'),[selected,setSelected]=useState(-1),[width,setWidth]=useState(1440);const touch=useRef(null);
  const visible=useMemo(()=>category==='all'?photos:photos.filter(photo=>photo.cat===category),[category]);const{columns,weights}=useMemo(()=>pack(visible,width),[visible,width]);const current=selected>=0?visible[selected]:null;const step=amount=>setSelected(index=>(index+amount+visible.length)%visible.length);
  useEffect(()=>{let frame=0;const resize=()=>{if(!frame)frame=requestAnimationFrame(()=>{frame=0;setWidth(innerWidth)})};setWidth(innerWidth);addEventListener('resize',resize);return()=>{cancelAnimationFrame(frame);removeEventListener('resize',resize)}},[]);
  useEffect(()=>{const key=event=>{if(!current)return;if(event.key==='Escape')setSelected(-1);if(event.key==='ArrowRight')step(1);if(event.key==='ArrowLeft')step(-1)};addEventListener('keydown',key);document.body.style.overflow=current?'hidden':'';return()=>{removeEventListener('keydown',key);document.body.style.overflow=''}},[current,visible.length]);
  return <><div className="gallery-controls"><div role="group" aria-label="Filter by subject">{categories.map(([value,label])=><button type="button" className={category===value?'is-active':''} aria-pressed={category===value} onClick={()=>{setCategory(value);setSelected(-1)}} key={value}><span>{label}</span><span>{String(value==='all'?photos.length:photos.filter(photo=>photo.cat===value).length).padStart(2,'0')}</span></button>)}</div><span>{String(visible.length).padStart(2,'0')} frames</span></div>
  <div className="gallery-grid">{columns.map((column,columnIndex)=><div className="gallery-column" style={{flex:weights[columnIndex]}} key={columnIndex}>{column.map((photo,index)=><button type="button" className="gallery-tile" style={{aspectRatio:photo.landscape?'4 / 3':'3 / 4',animationDelay:`${Math.min((index+columnIndex)*26,620)}ms`}} aria-label={`${photo.place} — ${photo.note}`} onClick={()=>setSelected(visible.indexOf(photo))} key={photo.id}><img src={photo.src} alt="" loading="lazy" decoding="async"/><i></i><span><small>{photo.number}</small>{photo.place}</span></button>)}</div>)}</div>
  {current&&<div className="lightbox" role="dialog" aria-modal="true" aria-label="Photo viewer" onTouchStart={event=>{const point=event.changedTouches[0];touch.current=[point.clientX,point.clientY]}} onTouchEnd={event=>{if(!touch.current)return;const point=event.changedTouches[0],dx=point.clientX-touch.current[0],dy=point.clientY-touch.current[1];if(Math.abs(dx)>46&&Math.abs(dx)>Math.abs(dy)*1.3)step(dx<0?1:-1);touch.current=null}}><header><span>{String(selected+1).padStart(2,'0')} / {String(visible.length).padStart(2,'0')}</span><div><button type="button" onClick={()=>step(-1)}>Prev</button><button type="button" onClick={()=>step(1)}>Next</button><span>Swipe or ← →</span><button type="button" className="lightbox-close" onClick={()=>setSelected(-1)}>Close</button></div></header><div className="lightbox-body"><figure><img src={current.src} alt={`${current.place} — ${current.note}`}/></figure><aside><small>{categories.find(([key])=>key===current.cat)?.[1]}</small><h2>{current.place}</h2><p>{current.note}</p><div>iPhone · {current.landscape?'4032 × 3024':'3024 × 4032'} · 12 MP · 2025</div></aside></div></div>}</>;
}
